---

plugins:
  - react
  - jest
  - babel

env:
  node: true
  jest/globals: true
  browser: true

parser: babel-eslint

parserOptions:
  ecmaFeatures:
    jsx: true
    modules: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:react/recommended'

rules:
  no-console: 0
